config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  get 'pages/about'

  resources :dogs
  resources :vets
  resources :owners

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/breed.rb
class Breed < ApplicationRecord
  has_many :dogs
end

# == Schema Information
#
# Table name: breeds
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/custody.rb
class Custody < ApplicationRecord
  belongs_to :owner
  belongs_to :dog
end

# == Schema Information
#
# Table name: custodies
#
#  id         :integer          not null, primary key
#  owner_id   :integer
#  dog_id     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_custodies_on_dog_id    (dog_id)
#  index_custodies_on_owner_id  (owner_id)
#

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :breed
  belongs_to :vet
  has_many :custodies
  has_many :owners, through: :custodies
  accepts_nested_attributes_for :custodies

  def last_name
    if custodies.empty?
      "(none)"
    else custodies.first.owner.last_name
    end
  end

end

# == Schema Information
#
# Table name: dogs
#
#  id         :integer          not null, primary key
#  name       :string
#  breed_id   :integer
#  dob        :date
#  weight     :string
#  vet_id     :integer
#  in_daycare :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_dogs_on_breed_id  (breed_id)
#  index_dogs_on_vet_id    (vet_id)
#

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :custodies
  has_many :dogs, through: :custodies


  def name
    "#{last_name}, #{first_name}"
  end

end

# == Schema Information
#
# Table name: owners
#
#  id              :integer          not null, primary key
#  first_name      :string
#  last_name       :string
#  phone           :string
#  address         :string
#  city            :string
#  state           :string
#  zip             :string
#  emergency_name  :string
#  emergency_phone :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

app/models/vet.rb
class Vet < ApplicationRecord
  has_many :dogs
end

# == Schema Information
#
# Table name: vets
#
#  id         :integer          not null, primary key
#  name       :string
#  clinic     :string
#  phone      :string
#  fax        :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  # GET /dogs
  # GET /dogs.json
  def index
    @dogs = Dog.all
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
    @dog.custodies.build
  end

  # GET /dogs/1/edit
  def edit
    @dog.custodies.build
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:name, :breed_id, :dob, :weight, :vet_id, :in_daycare, custodies_attributes: [:id, :owner_id, :_destroy])
    end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:first_name, :last_name, :phone, :address, :city, :state, :zip, :emergency_name, :emergency_phone)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/vets_controller.rb
class VetsController < ApplicationController
  before_action :set_vet, only: [:show, :edit, :update, :destroy]

  # GET /vets
  # GET /vets.json
  def index
    @vets = Vet.all
  end

  # GET /vets/1
  # GET /vets/1.json
  def show
  end

  # GET /vets/new
  def new
    @vet = Vet.new
  end

  # GET /vets/1/edit
  def edit
  end

  # POST /vets
  # POST /vets.json
  def create
    @vet = Vet.new(vet_params)

    respond_to do |format|
      if @vet.save
        format.html { redirect_to @vet, notice: 'Vet was successfully created.' }
        format.json { render :show, status: :created, location: @vet }
      else
        format.html { render :new }
        format.json { render json: @vet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vets/1
  # PATCH/PUT /vets/1.json
  def update
    respond_to do |format|
      if @vet.update(vet_params)
        format.html { redirect_to @vet, notice: 'Vet was successfully updated.' }
        format.json { render :show, status: :ok, location: @vet }
      else
        format.html { render :edit }
        format.json { render json: @vet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vets/1
  # DELETE /vets/1.json
  def destroy
    @vet.destroy
    respond_to do |format|
      format.html { redirect_to vets_url, notice: 'Vet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vet
      @vet = Vet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vet_params
      params.require(:vet).permit(:name, :clinic, :phone, :fax)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/vets_helper.rb
module VetsHelper
end

app/views/dogs/_form.html.erb
<%= simple_form_for(@dog) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.association :breed %>
    <%= f.input :dob %>
    <%= f.input :weight %>
    <%= f.association :vet %>
    <%= f.input :in_daycare %>
    <%= f.simple_fields_for(:custodies) do |custody_fields| %>
      <%= custody_fields.association :owner, collection: Owner.order(:last_name, :first_name) %>
      <% if custody_fields.object.persisted? %>
        <%= custody_fields.input :_destroy, as: :boolean %>
      <% end %>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Editing Dog</h1>

<%= render 'form', dog: @dog %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dogs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Breed</th>
      <th>Dob</th>
      <th>Weight</th>
      <th>Vet</th>
      <th>In daycare</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dogs.each do |dog| %>
      <tr>
        <td><%= dog.name %></td>
        <td><%= dog.breed %></td>
        <td><%= dog.dob %></td>
        <td><%= dog.weight %></td>
        <td><%= dog.vet %></td>
        <td><%= dog.in_daycare %></td>
        <td><%= link_to 'Show', dog %></td>
        <td><%= link_to 'Edit', edit_dog_path(dog) %></td>
        <td><%= link_to 'Destroy', dog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dog', new_dog_path %>

app/views/dogs/new.html.erb
<h1>New Dog</h1>

<%= render 'form', dog: @dog %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dog.name %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @dog.breed %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @dog.dob %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @dog.weight %>
</p>

<p>
  <strong>Vet:</strong>
  <%= @dog.vet %>
</p>

<p>
  <strong>In daycare:</strong>
  <%= @dog.in_daycare %>
</p>

<p>
  <strong>Owners:</strong>
  <ul>
    <%= @dog.owner.each do |owner| %>
    <li><%= owner.try(:name) %></li>
  </ul>
</p>


<%= link_to 'Edit', edit_dog_path(@dog) %> |
<%= link_to 'Back', dogs_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewDogDaycare</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render '/layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/owners/_form.html.erb
<%= simple_form_for(@owner) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :phone %>
    <%= f.input :address %>
    <%= f.input :city %>
    <%= f.input :state %>
    <%= f.input :zip %>
    <%= f.input :emergency_name %>
    <%= f.input :emergency_phone %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/owners/edit.html.erb
<h1>Editing Owner</h1>

<%= render 'form', owner: @owner %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Owners</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Phone</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Emergency name</th>
      <th>Emergency phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @owners.each do |owner| %>
      <tr>
        <td><%= owner.first_name %></td>
        <td><%= owner.last_name %></td>
        <td><%= owner.phone %></td>
        <td><%= owner.address %></td>
        <td><%= owner.city %></td>
        <td><%= owner.state %></td>
        <td><%= owner.zip %></td>
        <td><%= owner.emergency_name %></td>
        <td><%= owner.emergency_phone %></td>
        <td><%= link_to 'Show', owner %></td>
        <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
        <td><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Owner', new_owner_path %>

app/views/owners/new.html.erb
<h1>New Owner</h1>

<%= render 'form', owner: @owner %>

<%= link_to 'Back', owners_path %>

app/views/owners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @owner.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @owner.last_name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @owner.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @owner.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @owner.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @owner.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @owner.zip %>
</p>

<p>
  <strong>Emergency name:</strong>
  <%= @owner.emergency_name %>
</p>

<p>
  <strong>Emergency phone:</strong>
  <%= @owner.emergency_phone %>
</p>

<%= link_to 'Edit', edit_owner_path(@owner) %> |
<%= link_to 'Back', owners_path %>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/vets/_form.html.erb
<%= simple_form_for(@vet) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :clinic %>
    <%= f.input :phone %>
    <%= f.input :fax %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/vets/edit.html.erb
<h1>Editing Vet</h1>

<%= render 'form', vet: @vet %>

<%= link_to 'Show', @vet %> |
<%= link_to 'Back', vets_path %>

app/views/vets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Clinic</th>
      <th>Phone</th>
      <th>Fax</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vets.each do |vet| %>
      <tr>
        <td><%= vet.name %></td>
        <td><%= vet.clinic %></td>
        <td><%= vet.phone %></td>
        <td><%= vet.fax %></td>
        <td><%= link_to 'Show', vet %></td>
        <td><%= link_to 'Edit', edit_vet_path(vet) %></td>
        <td><%= link_to 'Destroy', vet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vet', new_vet_path %>

app/views/vets/new.html.erb
<h1>New Vet</h1>

<%= render 'form', vet: @vet %>

<%= link_to 'Back', vets_path %>

app/views/vets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vet.name %>
</p>

<p>
  <strong>Clinic:</strong>
  <%= @vet.clinic %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @vet.phone %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @vet.fax %>
</p>

<%= link_to 'Edit', edit_vet_path(@vet) %> |
<%= link_to 'Back', vets_path %>